
hl.on("hyprland.start", function ()
  hl.exec_cmd("uwsm app -- darkman run")
  hl.exec_cmd("uwsm app -- keepassxc")
  hl.exec_cmd("uwsm app -- awww-daemon; sleep 1; awww img $HOME/.config/hypr/wallpaper")
  hl.exec_cmd("uwsm app -- wl-paste --watch cliphist store")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface font-name 'JetBrainsMono Nerd Font 12'")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface font-name 'JetBrainsMono Nerd Font 12'")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrainsMono Nerd Font 12'")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Graphite-Dark'")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'")
end)
