animations {
    enabled = false
}

background {
    monitor =
    color = rgba(0, 0, 0, 1.0)   # Pure pitch black
}

# The Password Box
input-field {
    monitor =
    size = 350, 60
    outline_thickness = 2        # Thick brutalist outline
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 1.0)
    inner_color = rgba(0, 0, 0, 1.0)
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = false
    placeholder_text = <span foreground="white">ENTER PASSWORD</span>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
    rounding = 0
}

# The Clock
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1.0)
    font_size = 120
    font_family = JetBrainsMono Nerd Font Heavy
    position = 0, 100
    halign = center
    valign = center
}
